name: Rebase command

on:
  issue_comment:
    types: [created]

jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
      with:
        fetch-depth: 0

    - name: Automatic Rebase
      uses: cirrus-actions/rebase@99b0226479c59e6a40092b8afe704aabc61dec09
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
